routes:
  /: home
  /thank-you/: thank-you
  /about/: about

collections:
  /:
    template: home
    permalink: /
  /blog/:
    permalink: /blog/{slug}/

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/